language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: bjK9D0LIihUHCe5Yz+yzrYwY1MrLTRlgUxr/7sFRX5kLpxVNVg6apeLq8IViAIEpLKh8Hy6VbV8M+KDb8MB8EgMuNondYrIgUXD3nIVKp4SGJs3CNpp04vccawGReX9f2ivx5H7dlZIyTh5ngUbyoKTd2RW5VgOpjDMzPgAJX5qllN3hpVl3nYBy73BkTAKPH46EBrP4oMLeug3194eNf7rgoOCrqdzdNCnRhFjVFVMPoMDXZP/Du8BwkybyrRAIum2bKaeMUh2sp+TDebyMA/Wczn+VRRD1S9zv2jFfVxumebmdCxEke9G6jCYi81BNkuVTPZ4q7ro3AanPQw1vDayhyuxaGGuo3ivj+0npNrrUUYLVorPNMBE9V8DVBDQmYP/jPJTfqnfM9PLe54yXqjHOQRY277u0WnD6VtgFA/Qgu/9wjlZDJQ+Bcss/8qLSeL7i63rVShQGUihF0e8YgN+5Q3fHg5lLl9t4eyzqe98cyFBQBt5BTeUB+6a2HrxYxbHwrmEwGoJeLXSeg764iVN000Olp/SipaZ78id8E+p1mwc9ZUhMqJXwpYgpSJK8MgDvBKVfcitSR5ipEl9RdKDeBShTcaxNgy3j2eRUmahMOxSJWZsI7o7i6GerJUULPoJfWk3UswRo+GzWuMdz9gJhvwLvYb4v8Ts4AyNhQGc=
  app: secure-ravine-81156
  on:
    repo: TreyLiebscher/BlogPostAppWTests
